### ISSUE TITLE
Pretty fornat and confusion between d / delete and r / remove

### ISSUE THREAD

**Issue by ghost** [TorchlightSoftware/mongo-watch#15] opened 2014-10-22 17:08 UTC
When I choose pretty format, the operation delete is marked 'd' instead of 'delete'

in formats.coffee there is a case 'r' <=> 'remove', should it be 'delete' ?

**Comment by bitmage** [comment] 2014-10-28 16:07
Yes, it doesn't change the original data, just the keys:

https://github.com/TorchlightSoftware/mongo-watch/blob/master/lib/formats.coffee#L14

At this point, there may be people relying upon the current functionality, so it seems unlikely to justify a change.  Closing, as this works as intended.

**Closed as completed by bitmage** 2014-10-28 16:07 UTC
